### ISSUE TITLE
64-bit operating system requirement

### ISSUE THREAD

**Issue by bojeckkk** [kampersanda/xcdat#4]
Hey,

The frontpage for xcdat states:
```
The library considers a 64-bit operating system. The code has been tested only on Mac OS X and Linux. That is, this library considers only UNIX-compatible OS.
```
Is it a strict requirement? I would like to use the library on ARM32, so running under 32-bit OS.

**Comment by kampersanda** [comment]
@MrSherish

> Is it a strict requirement?

Maybe yes. This is because the Rank dictionary (implemented in [bit_vector.hpp](https://github.com/kampersanda/xcdat/blob/master/include/xcdat/bit_vector.hpp)) employs [Vigna's Rank9 implementation](https://vigna.di.unimi.it/ftp/papers/Broadword.pdf) that handles 64-bit words.

In Xcdat, however, all 64-bit words are handled using `std::uint64_t`. If `std::uint64_t` is simulated on your 32-bit environment, running Xcdat may be possible.

**Comment by jmr** [comment]
Maybe the requirements could be clarified to "requires `std::uint64_t` support" rather than "64-bit".
